package com.flawlesscoders.ambigu.table;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document(collection = "tables") 
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Schema(description = "This model represents tables")
public class Table {
    @Id
    @Schema(description = "Table id is autogenerated by the system")
    private String id;

    @Schema(description = "It's used to know the identification name of each table")
    private String tableIdentifier;

    @Schema(description = "Indicates the current status of the table")
    private TableStatus status;  

    public enum TableStatus {   
        OCCUPIED,
        UNOCCUPIED, 
        DISABLED
    }
}
