package com.flawlesscoders.ambigu.user.base;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Model that repsents the base user (used for login and related with admin and waiter)")
public class User {

    @Id
    @Schema(description = "User's id autogenerated by the database")
    private String id;
    @Schema(description = "User's email", example = "example@gmail.com")
    private String email;
    @Schema(description = "User's password")
    private String password;
    private Role role;
    private String name;
    private String lastname_p;
    private String lastname_m;
    private boolean isActive;
}
