package com.flawlesscoders.ambigu.order;

import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import com.flawlesscoders.ambigu.modules.user.waiter.Waiter;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Model that repsents the base order")
public class Order {
    @Id
    @Schema(description = "Order's id autogenerated by the database")
    private String id;

    @NotBlank(message = "Se debe de agregar una mesa a la orden")
    private String table;

    @NotNull(message = "Se deben de agregar platillos a la orden")
    private List<String> dishes;

    private Status status;

    private String comments;

    private float total;

    private Waiter waiter;

    private Opinion opinion;
}
