package com.flawlesscoders.ambigu.user.admin;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import com.flawlesscoders.ambigu.user.base.User;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "admins")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Model that represents the admin user")
public class Admin {
    @Id
    @Schema(description = "Admin's id autogenerated by the database")
    private String id;

    @DBRef
    @Schema(description = "DBRef to the user that is related to this admin")
    private User user;
}
