package com.flawlesscoders.ambigu.modules.table;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document(collection = "tables") 
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Schema(description = "This model represents tables")
public class Table {
    @Id
    @Schema(description = "Table id is autogenerated by the system")
    private String id;

    @NotBlank(message = "El nombre identificador de la mesa es obligatorio")
    private String tableIdentifier;

    @Schema(description = "Indicates the current client status of the table", defaultValue = "UNOCCUPIED")
    private TableClientStatus tableClientStatus;  //enum

    @Schema(description = "Indicates if the table is enabled or disabled", defaultValue = "true")
    private boolean isEnabled;

    @Schema(description = "Indicates if table has a waiter",  defaultValue = "false")
    private boolean tableWaiter;

}