package com.flawlesscoders.ambigu.modules.order;

import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "orders")
@CompoundIndexes({
    @CompoundIndex(name = "idx_finalized_table_deleted", def = "{'finalized': 1, 'table': 1, 'deleted': 1}"),
    @CompoundIndex(name = "idx_finalized_deleted_waiter_workplan", def = "{'finalized': 1, 'deleted': 1, 'waiterId': 1, 'workplan': 1}")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Model that repsents the base order")
public class Order {
    @Id
    @Schema(description = "Order's id autogenerated by the database")
    private String id;

    @Schema(description = "Order's number autogenerated by the database")
    private long orderNumber;

    @NotBlank(message = "Se debe de agregar una mesa a la orden")
    private String table;

    private String tableName;

    @NotNull(message = "Se deben de agregar platillos a la orden")
    private List<OrderDishes> dishes;

    private boolean finalized;

    private float total;

    private String waiter;

    private String waiterId;

    private String workplan;

    private Opinion opinion;

    private Date date;

    private boolean deleted;

    private String token;
}
